name: MiniGameCmdLib
version: '1.0.0-SNAPSHOT'
main: xyz.mlserver.miniGameCmdLib.MiniGameCmdLib
api-version: '1.21'

softdepend:
    - DecentHolograms

commands:
    set_block:
        description: MiniGameCmdLib command
        aliases:
            - sb
            - set-block
        permission: minigamecmdlib.command
    fill2:
        description: MiniGameCmdLib command
        aliases:
            - f2
            - fill-2
        permission: minigamecmdlib.command
    broadcast:
        description: MiniGameCmdLib command
        aliases:
            - bc
            - broadcast
        permission: minigamecmdlib.command
    glass_timer:
        description: MiniGameCmdLib command
        aliases:
            - gt
            - glass-timer
        permission: minigamecmdlib.command
    hologram_timer:
        description: MiniGameCmdLib command
        aliases:
            - ht
            - hologram-timer
        permission: minigamecmdlib.command
    reset:
        description: MiniGameCmdLib command
        aliases:
            - rs
            - reset
        permission: minigamecmdlib.command