name: MiniGameCmdLib
version: '1.0.0-SNAPSHOT'
main: xyz.mlserver.miniGameCmdLib.MiniGameCmdLib
api-version: '1.21'

commands:
    set_block:
        description: MiniGameCmdLib command
        usage: /<command> <subcommand> [args]
        aliases:
            - sb
            - set-block
        permission: minigamecmdlib.command